//spring.application.name=measurement

#DB_URL=jdbc:h2:mem:quantitydb
#DB_USERNAME=sa
#DB_PASSWORD=
#DB_DRIVER=org.h2.Driver
#POOL_SIZE=5

# Application
spring.application.name=quantity-measurement-app
server.port=8080

# H2 Database
spring.datasource.url=jdbc:h2:mem:quantitydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Enable 404 exception handling
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

springdoc.api-docs.enabled=true
spring.h2.console.settings.web-allow-others=true
springdoc.show-actuator=true
# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.com.app.quantitymeasurement=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Actuator
management.endpoints.web.exposure.include=health,metrics,info
management.endpoint.health.show-details=always

spring.security.oauth2.client.registration.google.client-id=YOUR_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=openid,profile,email

app.jwt.secret=mysecretkeymysecretkeymysecretkey12
app.jwt.expiration=86400000